# syntax = docker/dockerfile:1.4

FROM python:3.9-slim

WORKDIR /app

COPY ./app .

RUN pip install -r requirements.txt\
    && pip install virtualenv \
    && .venv/bin/activate


CMD ["uvicorn","main:app"]
